// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMs1De7VgvjVmc0b9OnMEN0lucO1NTMEU',
    appId: '1:754385778960:web:d9c6782ba890910b108d95',
    messagingSenderId: '754385778960',
    projectId: 'etrain-16b7a',
    authDomain: 'etrain-16b7a.firebaseapp.com',
    storageBucket: 'etrain-16b7a.firebasestorage.app',
    measurementId: 'G-571X8H3B16',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVHYxgxaXUi95GYPnjCUflPyuksrWse-M',
    appId: '1:754385778960:android:ad698a5125287b28108d95',
    messagingSenderId: '754385778960',
    projectId: 'etrain-16b7a',
    storageBucket: 'etrain-16b7a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFtaEPIvLG4m7E0XKkqRFd0zqggQKBWuI',
    appId: '1:754385778960:ios:364bc4f7d8c15d8c108d95',
    messagingSenderId: '754385778960',
    projectId: 'etrain-16b7a',
    storageBucket: 'etrain-16b7a.firebasestorage.app',
    iosBundleId: 'com.example.etrain',
  );
}
